version: "3"
services:
  postgres:
    image: "postgres:12.2"
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - "postgres"
    environment:
      - PORT=${API_PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}
  graphql:
    build:
      dockerfile: Dockerfile
      context: ./express-graphql
      args:
        PORT: ${GRAFQL_PORT}
    ports:
      - "${GRAFQL_PORT}:${GRAFQL_PORT}"
    environment:
      - PORT=${GRAFQL_PORT}
      - API_URL=https://api:${API_PORT}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - "graphql"
    environment:
      - HTTPSERVER_PORT=${FRONTEND_PORT}
