version: "3"
services:
  postgres:
    image: "postgres:12.2"
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - "postgres"
    environment:
      - DB_URL=${DB_URL}
      - PORT=8000
      - NODE_ENV=${NODE_ENV}
  graphql-server:
    build:
      dockerfile: Dockerfile
      context: ./express-graphql
    ports:
      - "4000:4000"
    environment:
      - API_URL=https://api:8000
